### ISSUE TITLE
Integrating jfxr in Gdevelop - a bit of help

### ISSUE THREAD

**Issue by blurymind** [ttencate/jfxr#35]
Hi,
I built the web app and am now getting it embedded in gdevelop.
Basically I need to get the json data of the sound effect and the base64 string of the wav file.
Then I need to be able to load the json data when angular opens and it was saved back to gdevelop in the past.
That is how it works for jsfx.

Because jfxr is an angular app, I am now wondering how do I access its controller and all of its methods in electron/nodejs? Is there a simple way to access the dom?

Sorry I dont have any previous Angular experience

**Comment by blurymind** [comment]
I  can find the methods I need inside bundje.js , but accessing bundle.js from another js seems a bit tricky

**Comment by blurymind** [comment]
Ok I managed to get to it with this ridiculous line:
`jfxr.angular.element(editorContentDocument.getElementsByClassName('ng-scope')[0]).scope().ctrl`
xD some progress

**Comment by blurymind** [comment]
now I can store the json data, however a bit stuck at writing the wav file.
toWavBytes doesnt seem to work, or I am not triggering it correct

**Comment by blurymind** [comment]
ok nevermind, I figured that out as well :) 
Might be able to do a pull some time this week :)

**Comment by blurymind** [comment]
I got this sorted now - will let you know when it gets merged :) 
closing this now, as I don't need help any more

**Comment by ttencate** [comment]
Hm, we're clearly not in the same time zone (I'm in Central European Time) :)

I didn't realise you wanted to integrate the entire app. I thought you just wanted the synthesis library. Glad you got it figured out!

FWIW, if I ever seriously continue development, I'll probably be porting the entire thing to Angular "2" or React or maybe Vue, which would break your embedding approach. At that point, we'll discuss adding some kind of proper API to the UI.

**Comment by blurymind** [comment]
Hi, i decided to embed the whole app in the end, as i figured it will be
faster than recreating the already awesome ui. :)
We might still use the library for the game engine side.

On upgrading- dont worry we will adopt to any changes you make to it. I
will share with you my pull request once its ready, so you can see how I am
interacting with the current interface. Gd will use the current version
until adjustments are made for any major upgrades

**Comment by blurymind** [comment]
Quick question - I am trying to decide on how to save jfxr sound resource data in gdevelop projects.
1. an url string to append to get the sound loaded (pro: its shorther, con: harder to read)
2. the original object, fetched via `jfxr.getSound().serialize()` (pro: clearer to read, con: longer)
This here is one of the older pulls where I made the jump
https://github.com/4ian/GDevelop/pull/716/commits/7cce6d1d97dbc4f0810552d8f38145f160c92a07

which of the two is more likely to be backwards compatible spec in future versions?

**Comment by ttencate** [comment]
It doesn't really matter I think; both go through the `MainCtrl` which is not a public API. Just use whichever is easiest for you.

**Comment by blurymind** [comment]
I went with storing the serialized object as a json sting :) it looks cleaner.
Btw the analytics script you have attached to the app was causing issues with embedding it:
https://github.com/4ian/GDevelop/pull/716#issuecomment-433731265

Basically the iframe's onload signal gets massively delayed 50% of the time when the app is inside an iframe, inside an electron window instance - due to the analytics script. One way I found around it is in using a timer instead
https://github.com/4ian/GDevelop/pull/716/commits/03c6e7cb7b9aa8e1828212c84d783663105f3908

Would it be possible perhaps - if we have this script, to also have a signal emited when the ctrl element is loaded? That way we will be able to get it in a cleaner way- on the frame it happens :)

**Comment by ttencate** [comment]
That's odd. The Google Analytics script is loaded `async` so it shouldn't be delaying anything:

      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create','UA-19568648-1','auto');ga('send','pageview');

I'll add an event that you can listen to, which will be fired after initialization of the main controller, like this:

    document.addEventListener('jfxrReady', (e) => { console.log(e.mainCtrl); });

**Comment by 4ian** [comment]
> I'll add an event that you can listen to, which will be fired after initialization of the main controller, like this:

Looks great! Thanks for adding this, should make things more robust. @blurymind let me know if you have time to try it :)

**Comment by blurymind** [comment]
I can do it after work in a few hours, if its added to jfxr :)

**Comment by blurymind** [comment]
Thank you for doing that btw. We are getting really close to a merge now

**Comment by blurymind** [comment]
Ok I gave this a try and using the signal like this:
`document.addEventListener('jfxrReady', (e) => { console.log(e.mainCtrl); });`
nothing prints out.
Using it like this
```
document.getElementById('jfxr-frame').contentWindow.addEventListener('jfxrReady', (e) => {
  console.log(e.mainCtrl);
  console.log('received'); 
});
```
80% of the time it doesnt run the console.logs in dev mode. Not sure why

I even tried
```
const editorFrameEl = document.getElementById('jfxr-frame')
editorFrameEl.onload= ()=>{
  document.getElementById('jfxr-frame').contentWindow.addEventListener('jfxrReady', (e) => {
    console.log(e.mainCtrl);
    console.log('received'); 
  });
}
```

**Comment by blurymind** [comment]
@ttencate thank you for taking the time to explain this, I will give it another try after work tonight and do another commit.

>  This is too late to catch jfxrReady. And it would probably include even async scripts like Google Analytics, which explains your earlier slowdowns.

Yes indeed that was what I tried using before the timer solution in my last commit and 50% of the time it got delayed by 10-20 seconds on the electron build.

Using iframes in general is not ideal, but at least allows us to keep the external editors' code vanilla :)

**Comment by blurymind** [comment]
@ttencate trying that now the signal never actually fires :( 
Inside jfxr-main.js, add this:
```
document.getElementById('jfxr-frame').contentWindow.addEventListener('jfxrReady', (e) => {
  console.log(e.mainCtrl);
  console.log('received'); 
});
document.getElementById('jfxr-frame').src = 'jfxr-editor/index.html'
```
nothing prints out.
Inside the index file, you can try moving the script before the dom, after the dom - just doesn't fire.

**Comment by 4ian** [comment]
> I suggested to @4ian to just use the timer approach for now, as it is more reliable than anything else - if it's ok by you as well. Even with your signal this is turning out to be tricky with the current implementation

I'm ok for using the timer/retry approach as it's not noticeable. Would be interesting to push a bit more to search if we can reach a good solution without it. If we can't that's fine, the solution with setInterval will do the job and don't have a real impact other than being not as "clean" as it could (in theory).

**Comment by blurymind** [comment]
To the end user it loads really fast even with polling :) The timer approach seems more solid even when the signal does work most of the times.
I used a signal on piskel and some times- even rarely - when you load it from gdevelop- it doesnt load the sprites most probably because of the same reason. But if you close it and reopen it- it loads them.
It's almost the same number of lines of code, so its really not making it harder to maintain or understand imo

**Comment by blurymind** [comment]
I tried it with the signal after the latest commits to jfxr and it works flawlessly now. I made the gdevelop embedding use the signal now.
@ttencate fantastic work!
@4ian we are ready for review :) 👍
