### ISSUE TITLE
Play preview sound on release of slider, not during drag

### ISSUE THREAD

**Issue by blurymind** [ttencate/jfxr#39]
Right now when you change a parameter, the sound plays as you drag the slider. This results in the sound being repeated over itself - not playing to the end until you release it.

I think it will be generally better to hear it from start to end when the mouse releases the slider instead of as you are dragging it.
That way the sound will play from start to end clearly and we wont have to click on the play button after that to hear it out properly

**Comment by ttencate** [comment]
Agreed. This is not entirely trivial because of the way Angular works (we need the model to change because we want to update the numbers during slider changes), but of course it can and should be done.
