### ISSUE TITLE
Export and save always downloads a new file instead of overwriting the "opened" file

### ISSUE THREAD

**Issue by fatlard1993** [ttencate/jfxr#47]
If I open a file (that is no longer in my downloads folder) I want to be able to save to the file location I opened. The way it is now works but I then have one extra step to move the newly downloaded file into the location I'm using it

**Comment by ttencate** [comment]
That would be great, but I'm afraid this is not something I can fix. The browser doesn't tell the webpage the full path of the file, only the file name. Similarly, upon saving, there's no way for the webpage to tell the browser the path where to save the file, only the file name. The browser then decides whether to open a save dialog, or put the file straight into the Downloads folder.

**Comment by fatlard1993** [comment]
Got it, thanks. Was unaware of that limitation. I have read into it a bit more now that its been brought to my attention. I've found a decent workaround that others may find useful:

Temporarily change your browser download location.
